### ISSUE TITLE
Is the event bus a logger here?

### ISSUE THREAD

**Issue by armaandh** [vtuanjs/typescript-solid-architecture#1]
Awesome project. Just wondering what the main use case for your event bus is supposed to be. Is it to log events of various actions? For example, in the login method you use the event bus. Wondering what the use case is here.

**Comment by tuan-nguyen-egany** [comment]
Thank you for asking. Event Bus (Queue) helps the system to reduce the load and communication to another service.
In production, "Activity Service" (You can call Logging Service) will be deployed at another service. Event bus helps service A communication with "Activity Service" easily!

**Comment by vtuanjs** [comment]
Solved
